version: '3.8'

services:
  postgres:
    image: 'ankane/pgvector:v0.5.0'
    restart: always
    environment:
      - POSTGRES_DB=vector_store
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - PGPASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
    container_name: postgres

  spring-app:
#    image: rag-back
    image: delmas007/rag-back:v2.0
    ports:
      - '7788:7788'
    depends_on:
      - postgres
    networks:
      - my-network
    container_name: spring-app
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL=${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL}
      - SPRING_AI_OPENAI_CHAT_OPTIONS_TEMPERATURE=${SPRING_AI_OPENAI_CHAT_OPTIONS_TEMPERATURE}
      - SPRING_AI_OPENAI_CHAT_OPTIONS_MAX_TOKENS=${SPRING_AI_OPENAI_CHAT_OPTIONS_MAX_TOKENS}
      - SPRING_AI_OPENAI_CHAT_OPTIONS_TOP_P=${SPRING_AI_OPENAI_CHAT_OPTIONS_TOP_P}
      - SPRING_AI_OPENAI_CHAT_OPTIONS_FREQUENCY_PENALTY=${SPRING_AI_OPENAI_CHAT_OPTIONS_FREQUENCY_PENALTY}
      - SPRING_AI_OPENAI_API_KEY=${SPRING_AI_OPENAI_API_KEY}
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
      - RSA_PUBLIC_KEY=${RSA_PUBLIC_KEY}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}


  angular-app:
    image: delmas007/rag-front:v2.0
#    image: rag-front
    ports:
      - '4200:4200'
    depends_on:
      - spring-app
    networks:
      - my-network
    container_name: angular-app

networks:
  my-network:
    driver: bridge

volumes:
  pgdata:
